services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: book-library-backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    image: book-library-frontend 
    ports:
      - "3000:3000"

  